### ISSUE TITLE
Determine leadership and budget requirements needed to manage the program.

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/administration#1]
Our primary goal is to create a sustainable project learning and training program for Drupal. To reach that goal we need to determine the staffing and budget requirements needed to keep such a program operational and sustainable.  

Let's work out the details in this [google doc](https://docs.google.com/document/d/1LrShmkSJ4ewaUNSDtNX0UD1P-W7d0fvsw1blrdmkRn8/edit?usp=sharing) and finalize [in the wiki](https://github.com/DrupalOpenLearning/administration/wiki/Drupal-Open-Learning-program-staff)

**Comment by gusaus** [comment]
A majority of the ongoing work at all levels could be done by students and volunteers; even high level development roles could be done by folks who like to volunteer in their free time or their company allocates them time.

So we really need to identify and budget for the essential roles needed manage the program and the internal sites. For the latter the paid leads would mainly be teaching or mentoring. 

With that said, we should probably add roles pertaining the managing/maintaining the websites and the learning program. 

As we'll be doing the latter in collaboration with members of the [ELMS Learning Network](https://github.com/elmsln), possibly @btopro could help define that and other roles needed for [Open Ulmus](https://github.com/elmsln/openulmus.org/issues/2)?

**Comment by gusaus** [comment]
I've taken an initial stab at breaking down the operational roles https://github.com/DrupalOpenLearning/administration/wiki/Drupal-Open-Learning-program-team

What do you think about the program manager role shared between @mmilutinovic1313 @ikit-claw @lyndsey and myself?

**Comment by mmilutinovic013** [comment]
This sounds reasonable to me. I think a combined effort will help this all get off the ground.

**Comment by gusaus** [comment]
I wanted to post @cleverington's follow up to a discussion about this GitBook he put together for the Drupal Diversity group https://www.gitbook.com/book/drupal-diversity/drupal-organizer-resources/details

> I actually built out the infrastructure of that GitBook using experience with my own: https://github.com/cleverington/n00b-drupal-development

> Would be happy to refactor the n00b’s guide (or just portions of the content therein) into a more communal project for Drupal Dojo’s use.  Can help configure it / set it up to where the only thing we’d have to worry about from there is **content**.

In addition to both guides being something we could build upon, we need a much better system for managing, organizing, and sharing our documentation and guidelines. 

Based on that, I'm wondering if this is a role that @cleverington could also take on. One of the first tasks could be devising a better system for defining roles (as opposed to wikis scattered about several related projects).

**Comment by gusaus** [comment]
Closing this out as we're moving back to the newly re-opened project on drupal.org. If you have an interest in being one of the program leads (goal is to secure a budget for 5-10hrs/wk paid time for each lead), chime in here https://www.drupal.org/node/317489
