### ISSUE TITLE
Establish process for open collaborative development and documentation

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/administration#5]
The following was the first stab in terms of establishing guidelines and a workflow for open drupal development. Even though some elements are a bit stale, I 'think' the following wiki could be updated.

https://groups.drupal.org/node/8051

**Comment by gusaus** [comment]
I think this bit from @cleverington is relevant to issue - 

>if ya'll want to create a GitBook, the only thing you need is a repository we can post to.  We can even write the whole thing in a Google Doc, because I've got a script which will print a Google Doc (images and all) out into a downloadable ZIP file, which I can then convert into a GitBook.  That's how we did it with the https://drupal-diversity.gitbooks.io/drupal-organizer-resources/content/

First off, we need a process for creating and collaborating on docs and guidelines. Scattered wikis on g.d.o. and github probably aren't ideal. Should we start with a google doc? We would like to both use and teach whatever would be consider best practice. 

Also seems like most of the docs and guidelines we're working on for our programs (including this one) could not only be source material for our initial courses https://github.com/elmsln/openulmus.org/issues/5, they also could reside in a variation of this Gitbook https://cleverington.gitbooks.io/n00b-drupal-development/content/

**Comment by cleverington** [comment]
I think I would recommend a segmented approach.

# Initial

Aggregate existing / current / past resources in a link farm (this issue?).

# Define Scope

Based on this issue, and reading the old page, I would have the book separated based on Roles:
- General Resources
- Project Lead / Manager
- Mentor
- Mentee
- Collaborative Development
- Documentation
- Contribute
  - Instructions for Contributors

# Tracking

On your more globalized Project Management & Mgmt of Mentor/Mentee Programs, it might be more beneficial to use a more full-featured Kanban board like trello.com over trying to use GitHub's Projects.  (Mentors, active projects, etc.)

From experience, GitHub Projects gets stacked QUICKLY when trying to use it for administrative management.  Using it just for code / projects is cool though.

# Teaching

(In my experience, zero research here...) 
n00bs like uncluttered resources.
n00bs and students like defined "This is A, this is B" instructions, even if those instructions force them to search twenty different pages in ugly/cluttered sites to learn *why*. While _doing_ and _learning_, the *why* is not important.  A 'Resources' section at the end of each page helps best.

# Document/Page Templating & Contributing

As it is a shared resource that should be referenced often if giving tutorials to n00bs, I would recommend using the same layout/template and Contribution Guidelines as the Documentation Team used when creating the Drupal 8 User Guide.

https://www.drupal.org/docs/user_guide_guidelines/index.html 

We could even simply use those and have a 'Dojo Flavored' changes, as needed.

More later. Gotta jet!

**Comment by gusaus** [comment]
@cleverington Does that seem in scope with the gitbook you've been putting together? I envision these materials residing on the Drupal Open Learning site https://github.com/DrupalOpenLearning/administration/projects/3, which will house all Drupal related courses. https://github.com/elmsln/openulmus.org/issues/14

Agreed a good deal of resources can be pulled from (and contributed back) to Drupal docs. Also think there's a good bit of overlap and room for collaboration with the DDI contrib team https://github.com/drupaldiversity/contrib/issues/2 https://github.com/drupaldiversity/contrib/issues/18

Would you be interested in heading this up and helping bridge these complimentary community efforts? https://github.com/drupaldiversity/administration/issues/135#issuecomment-329823476

**Comment by cleverington** [comment]
@gusaus Probably onboarding confusion from my part.

To clarify (and part of that mind-map I mentioned in Slack), if I've gathered enough data: 

## Supporting Projects
1. ELMS: Learning Network
  - Backbone infrastructure for OpenLearning
  - Backbone infrastructure for Drupal Open Curriculum


## Programs (Spaces)

1. Drupal Open Curriculum
  - Aggregation of learning resources used via other projects and available globally.
  - Aggregation and Documentation of Training Resources for OpenLearning
  - I think I would see those Templating standards here....?
2. OpenLearning
  - Consulting and Services for Training Programs
  - Social Training Platform for Drupal-based Courses (via ELMS)
  - Platform for organizing and facilitating Paid Internship Projects
3. DrupalDojo
  - Consulting, Services, and Social Media for Drupal Community Collaboration
  - Consulting, Services, and Social Media for Drupal Community Mentorship Program
  - Project Management and Platform for Drupal Community Mentorship Program
  - Link farms for Mentors
  - Link farms for Mentees

## Actual Reply

As for bridging with DDI, I can certainly provide a point of contact, though leadership / decisions in the group are with others.

**Comment by gusaus** [comment]
Closing and will reference this issue on d.o. https://www.drupal.org/node/206506
