### ISSUE TITLE
Create guidelines for online workshops, mentoring, and sprints

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/administration#7]
As Josh Koenig [mentioned in #drupal-dojo](https://drupal.slack.com/archives/C5NR9LLNT/p1499471714301541) we'd like to use [Twitch.tv](https://www.twitch.tv/) as the streaming event platform. 

He followed up with a [suggested process](https://drupal.slack.com/archives/C5NR9LLNT/p1499716028866747) - 
> We’d have a Drupal Dojo community I think. People have their own twitch accounts as individuals, and then we let them stream into the community. Their tech for all this is actually very nice. It’s come a long way since the days of custom java appservers powering VNC + group skype calls.

Similarly [Lyndsey suggested another scenario](https://drupal.slack.com/archives/C5NR9LLNT/p1499822538998335) where live Twitch sessions could be valuable 
>Id be interested in watching some really good builders build/code. And particularly if there was a remote sprint around it. So highlight a module/stuff in issues queue and have a core maintainer going through what they look at in code, how they approach review, and encourage others to be working on issues at same time.

>So something like accessibility for example, it takes a different way of thinking and testing. There is code and function to review. What are maintainers testing for, what's a pass, what's an ignore, what's the cascading effects from that.

>I don't code but there are a couple of people in the accessibility space that if be fascinated to watch work and have share and talk through their knowledge
 
>Live coding/working is cool because you don't have to be presenting as such, just good at working and explaining what you are doing. It can be organic

Based on this we need to create some guidelines for community members who'd like to use Twitch.tv for these types of learning sessions. This post may provide some inspiration - 
https://medium.freecodecamp.org/lessons-from-my-first-year-of-live-coding-on-twitch-41a32e2f41c1

**Comment by gusaus** [comment]
@trevortwining If you're interested/able to produce a weekly live Dojo, possibly you can take on or delegate this task?

We can work on the format, sponsor parameters, line up presenters, figure out what other support you would need.

**Comment by ikit-claw** [comment]
@gusaus when it comes to twitch you also need to take into consideration stream quality and duration of events. I can't speak for everyone but I know I have had issues with streaming for over 2hours because of the bandwidth required and my provider I need to find a good profile for a 720p stream settings so I can do some streaming without interruption. Something to be aware of if you have streamers capable of 1080p is that they might hit a bandwidth limit.

**Comment by ikit-claw** [comment]
@gusaus I will do the twitch guide in the next 24 hours.

**Comment by ikit-claw** [comment]
Twitch guide complete.

**Comment by gusaus** [comment]
https://github.com/DrupalOpenLearning/drupaldojo/wiki/Setting-up-your-Twitch-and-OBS-for-stream-recording looks great! 

Per https://github.com/DrupalOpenLearning/drupaldojo/issues/7#issuecomment-324459863 it would be good to have a Drupal Dojo specific wiki in the Drupal groups.

**Comment by gusaus** [comment]
Closing and referring back to the following issues - 

Production guidelines for live sessions and lessons - https://www.drupal.org/node/414722
Production guidelines for educational videos - https://www.drupal.org/node/201890
