### ISSUE TITLE
Building the Drupal Dojo class

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/administration#8]
One of our major objectives is to create a curriculum and complete set of training materials derived from the process of building new sites for our program. We'd like to provide hands on training in areas ranging from site planning, drafting proposals, project management, information architecture, development, design, infrastructure, to community, business, marketing, and program development.

To do this properly we should 

- [ ] work with @btopro to find someone from [ELMS Learning Network](https://github.com/ELMSLN) to head up the instructional design. 
- [ ] estimate the time/cost to develop curriculum using [this old plan](https://groups.drupal.org/node/22434) as a guide
- [ ] estimate the time/cost to produce live workshops, learning sessions, and videos  #7 

We can add specific action items based on subsequent thoughts and comments....

**Comment by btopro** [comment]
@kat-wehr would be who I'd nominate to see if she has interest in doing ID work for this effort. If interested talk to Gus to find out more Katrina.

**Comment by gusaus** [comment]
@btopro I think it would be best for @kat-wehr and any potential leads to join #elmsln and #drupalopenlearning in https://slack.opencollective.com/.

Will be easier to converse about this and related projects in a group consisting of people that have a clue how to properly go about it!

**Comment by kat-wehr** [comment]
@gusaus I'm already on the slack channel as kat-wehr :) Would love to chat about this and try to get the scope figured out. I'll @ mention you there as well.

**Comment by gusaus** [comment]
Thanks @kat-wehr! Hopefully what I've mentioned in Slack provides a little more background regarding how these projects/programs overlap. Based on [feedback from Josh](https://github.com/DrupalOpenLearning/drupaldojo/issues/1#issuecomment-319814416) I think we'll table the ambitius plan of making the entire site build sort of a real time learning project. 

Better to build the MVP Drupal Dojo and [Open Ulmus](https://github.com/elmsln/openulmus.org/issues/1) as quickly as possible. Then go back and create curriculum and training materials that documents how we set it up?

Let me know here or in Slack if that gives you a better idea of the initial scope.

**Comment by ikit-claw** [comment]
I think a big blocker is that we are thinking so large scale that we aren't doing much other than talking about the project. When we have the basics of what we need already.

**Comment by gusaus** [comment]
@ikit-claw Generally speaking, the blocker has been not having the resources or model to sustain a team to manage the program. We're resolving with   #1 

With regards to producing tutorials, curriculum, training, etc, per my previous comment I agree we should first focus on https://github.com/DrupalOpenLearning/drupaldojo/issues

**Comment by gusaus** [comment]
@mmilutinovic1313 Assuming we're going to centralize courses in Open Ulmus https://github.com/elmsln/openulmus.org/issues/14#issuecomment-338035878, we should set up an issue to scope out this course.... then copy over anything worthwhile and close.

Linked in the issue descritpion is the original course outline https://groups.drupal.org/node/22434

Not sure if that has any value.

**Comment by mmilutinovic013** [comment]
That has a lot of value - I will take a look at this in more detail and then close the issue at hand 😄

**Comment by gusaus** [comment]
@mmilutinovic1313 We should definitely check to see if the same potential ID has current availability and interest once we get our scope worked out! https://github.com/DrupalOpenLearning/administration/issues/8#issuecomment-319951351

**Comment by mmilutinovic013** [comment]
Hey @kat-wehr! Feel free to send me a message on slack or here if you are still interested in the ID role for this project. I think we are making some headway and I can help fill you in on the scope.

**Comment by gusaus** [comment]
Closing and referring back to the d.o. issue https://www.drupal.org/node/322495

We might also want to close and open a new issue for that task.
